import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Container, Box } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>TechneApp official website</title>
      </head>
      <body
        style={{ margin: 0, padding: 0, width: "100vw", overflowX: "hidden" }}
      >
        <Header />
        <Box
          component="main"
          sx={{ minHeight: "80vh", width: "100%", padding: 0, margin: 0 }}
        >
          {children}
        </Box>
        <Footer />
      </body>
    </html>
  );
}
